export const SUBTITLE_REDUCER = 'subtitleReducer';
export const SUBTITLE_REDUCER_TYPE = {
  ADD: 'ADD',
  ORDER_UP: 'ORDER_UP',
  ORDER_DOWN: 'ORDER_DOWN',
  REMOVE: 'REMOVE',
  CHANGE_OPTION: 'CHANGE_OPTION',
  WRITE_SONG: 'WRITE_SONG',
  WRITE_TITLE_JP: 'WRITE_TITLE_JP',
  WRITE_TITLE_KR: 'WRITE_TITLE_KR',
  WRITE_MENTION_JP: 'WRITE_MENTION_JP',
  WRITE_MENTION_KR: 'WRITE_MENTION_KR',
}
export const ACTION_SUBTITLE_WRITE_SONG = `${SUBTITLE_REDUCER}/${SUBTITLE_REDUCER_TYPE.WRITE_SONG}`;
export const ACTION_SUBTITLE_WRITE_TITLE_KR = `${SUBTITLE_REDUCER}/${SUBTITLE_REDUCER_TYPE.WRITE_TITLE_KR}`;
export const ACTION_SUBTITLE_WRITE_TITLE_JP = `${SUBTITLE_REDUCER}/${SUBTITLE_REDUCER_TYPE.WRITE_TITLE_JP}`;
export const ACTION_SUBTITLE_WRITE_MENTION_KR = `${SUBTITLE_REDUCER}/${SUBTITLE_REDUCER_TYPE.WRITE_MENTION_KR}`;
export const ACTION_SUBTITLE_WRITE_MENTION_JP = `${SUBTITLE_REDUCER}/${SUBTITLE_REDUCER_TYPE.WRITE_MENTION_JP}`;
export const ACTION_SUBTITLE_CHANGE_OPTION = `${SUBTITLE_REDUCER}/${SUBTITLE_REDUCER_TYPE.CHANGE_OPTION}`;
export const ACTION_SUBTITLE_ADD = `${SUBTITLE_REDUCER}/${SUBTITLE_REDUCER_TYPE.ADD}`;
export const ACTION_SUBTITLE_REMOVE = `${SUBTITLE_REDUCER}/${SUBTITLE_REDUCER_TYPE.REMOVE}`;
export const ACTION_SUBTITLE_ORDER_UP = `${SUBTITLE_REDUCER}/${SUBTITLE_REDUCER_TYPE.ORDER_UP}`;
export const ACTION_SUBTITLE_ORDER_DOWN = `${SUBTITLE_REDUCER}/${SUBTITLE_REDUCER_TYPE.ORDER_DOWN}`;
